### ISSUE TITLE
Styling <ngx-img>and Increase file size limit.

### ISSUE THREAD

**Issue by UNADYNE** [harryy2510/ngx-img#1]
This is an awesome and easy to use tool.  Thank you for creating it.  I would like to be able to style the element/s that you have made.  I have tried to target them with css and js but to no avail.  

I would also like to increase the size of the uploaded file to > 2048.

please help.

Thank you.

**Comment by harryy2510** [comment]
Please check the [documentation](https://harryy2510.github.io/ngx-img/home) on how to increase file size limit.

For the styling part, you can overwrite the classes I've written.
