### ISSUE TITLE
Reset Image from File

### ISSUE THREAD

**Issue by aparkertg** [harryy2510/ngx-img#10]
First I want to mention this plugin works great, exactly what I was looking for.

I placed this plugin in a modal. When a user presses an 'upload' button, the modal presents the image cropper and uploader - no issues.

The problem comes when the user opens the modal to upload another photo. The last image that was uploaded is automatically loaded in the cropper. The user has to press the "remove" button to reset the image in order to load another.

Normally this isn't a problem, however I have two upload buttons on the same page for different modals, different components. If the user uploads a photo in one modal, when they click on the next upload button the plugin doesn't work. The image they try to upload is displayed but the cropper functionality disappears. The only way to remedy this is the user has to open the original modal, and click the remove button. Then it'll work.

This happens often. I would like to trigger the "remove" button every time the plugin is accessed programmatically. Could you point out how to do this?

Thanks.

**Comment by yashwp** [comment]
@aparkertg When you will destroy your modal which contains it, it should automatically reset.

**Comment by aparkertg** [comment]
@yashwp The modal is loaded when the page is generated, and then it's hidden or revealed when the user presses the button (not destroyed). Therefore the ngx-img is loaded when the page is generated, so it is not destroyed when the modal is hidden.

That's why I asked about reseting the cropper's image data programmatically (e.g. the remove button). So I can clear the img data completely whenever needed (instead of waiting on the user, or destroying the element).

But as you stated in the mean time I'm destroying the cropper element to reset the image data to get it working.

**Comment by soyJairoCosta** [comment]
I have the same problem over here.

I have two editors in the same component... And when I try to choose the second image, the plugin behaviour is the same that @aparkertg wrote.

**Comment by yohitan12** [comment]
Good morning, one of you was able to solve this problem. Could you help me with some code to do it?

**Comment by harryy2510** [comment]
For resetting to default state, the component needs to be destroyed and created again.
