### ISSUE TITLE
package.json incorrect config

### ISSUE THREAD

**Issue by UNADYNE** [harryy2510/ngx-img#2]
### Bug Report or Feature Request (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?

> Windows 10

### Versions

1.6.x

### Repro steps

yarn add ngx-img
because npm won't install it

### The log given by the failure
{
  "name": "ngx-img",
  "version": "10.0.3",
  "description": "Angular Image Upload &amp; Crop",
  "keywords": [
    "angular",
    "image",
    "upload",
    "crop"
  ],
  "author": {
    "name": "Hariom Sharma",
    "url": "http://github.com/harryy2510"
  },
  "repository": {
    "type": "git",
    "url": "git://github.com/harryy2510/ngx-img.git"
  },
  "license": "MIT",
  "bugs": {
    "url": "http://github.com/harryy2510/ngx-img/issues"
  },
  "homepage": "http://github.com/harryy2510/ngx-img",
  "main": "bundles/ngx-img.umd.js",
  "module": "ngx-img.es5.js",
  "es2015": "ngx-img.js",
  "typings": "ngx-img.d.ts",
  "peerDependencies": {
    "@angular/common": "^^4.4.6",
    "@angular/compiler": "^^4.4.6",
    "@angular/core": "^^4.4.6",
    "@angular/forms": "^^4.4.6",
    "@types/cropperjs": "^^1.1.0",
    "cropperjs": "^^1.1.3"
  }
}

### Mention any other details that might be useful
for some reason when installing the package the package.json file looks like this, which causes the problems one would expect.  I have gotten it to work by manually editing package.json and installing cropperjs and @types/cropperjs but every time I install or update another package ngx-img reverts to this state.

**Comment by harryy2510** [comment]
Resolved!
