### ISSUE TITLE
Set default crop to full image (i.e. no crop)

### ISSUE THREAD

**Issue by jacksonhart** [harryy2510/ngx-img#20]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
```

### OS and Version?
Windows 10

### Versions
10.19

### Repro steps
load any image

### Desired functionality
A setting so when an image initially loaded, the crop window is the same size as the image instead of taking up the middle 80%.
So it only needs to be resized if there is any cropping to be done.

**Comment by harryy2510** [comment]
Fixed in v10.19.3
