### ISSUE TITLE
Add initial preview on imgSrc, before showing the upload 

### ISSUE THREAD

**Issue by cintolas** [harryy2510/ngx-img#3]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
```

### OS and Version?

Mac High Sierra

### Versions

  
Angular CLI: 1.7.3
Node: 6.12.3
OS: linux x64
Angular: error
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

### Desired functionality
When creating the component I would like to add a default imgSrc that would be available when the element is created.  

We have an edit dialog box that allows you to upload an icon for use.  ngx-img works great for uploading.  However, when editing an existing object, our icon itself is already available.  The user can delete the icon or upload a different one

I tried setting  imgSrc, but it did not do anything.  Is there a way I can accomplish this?

**Comment by harryy2510** [comment]
Sorry for replying late. I have been quite busy last few days. For now, it is not possible but will definitely add functionality of default image source.

**Comment by soyJairoCosta** [comment]
Any update on this enchancement?

**Comment by harryy2510** [comment]
There's a newer version coming soon with alot of great features.

**Comment by cintolas** [comment]
do you have an estimated release date on the new release?

**Comment by ziomyslaw** [comment]
Probably a duplicate #14  
Check answer there.

**Comment by yashwp** [comment]
Refer to [https://github.com/harryy2510/ngx-img/issues/14](url). Hence closing this issue
