### ISSUE TITLE
Can't resolve 'cropperjs'

### ISSUE THREAD

**Issue by glynthink** [harryy2510/ngx-img#6]
Bug after installation

ERROR in ./node_modules/ngx-img/ngx-img.es5.js
Module not found: Error: Can't resolve 'cropperjs' in '(project)\node_modules\ngx-img'

Angular CLI: 6.0.5
Node: 8.11.1
OS: win32 x64
Angular: 6.0.3

**Comment by pauranik51** [comment]
Have you tried running gulp command once?

**Comment by harryy2510** [comment]
try

```
npm install cropperjs --save
```
